#require_block
require_relative 'regex_object'
require_relative 'pattern_literal'
require_relative 'pattern_plus'
require_relative 'pattern_star'
require_relative 'pattern_dot'
require_relative 'pattern_start'
require_relative 'pattern_end'
require_relative 'pattern_composite'
require_relative 'scanner'
require_relative 'compiler'
